const PORT_NUM = process.env.port || process.env.PORT_NUM;

//Shopify Configs
const SHOPIFY_API_KEY = process.env.SHOPIFY_API_KEY;
const SHOPIFY_SECRET_KEY = process.env.SHOPIFY_SECRET_KEY;
const SHOPIFY_API_TOKEN = process.env.SHOPIFY_API_TOKEN;
const SHOPIFY_API_SCOPES = process.env.SHOPIFY_API_SCOPES;
const SHOPIFY_SHOP_NAME = process.env.SHOPIFY_SHOP_NAME;

//DB Configs
const DB_HOST_URL = process.env.DB_HOST_URL;
const DB_NAME = process.env.DB_NAME;
const DB_USERNAME = process.env.DB_USERNAME;
const DB_PORT_NUM = process.env.DB_PORT_NUM;
const DB_PASSWORD = process.env.DB_PASSWORD;
const DB_CERTIFICATE =
  `-----BEGIN CERTIFICATE-----
MIIEQTCCAqmgAwIBAgIUOi4Aqdf3BxEp4nfpeFYGpvuWhFYwDQYJKoZIhvcNAQEM
BQAwOjE4MDYGA1UEAwwvMjEyODYwNDQtOTU4Zi00Y2JlLTgyZjQtZWFlZjJlZGIx
MDFkIFByb2plY3QgQ0EwHhcNMjQwODI1MTI0MDQ0WhcNMzQwODIzMTI0MDQ0WjA6
MTgwNgYDVQQDDC8yMTI4NjA0NC05NThmLTRjYmUtODJmNC1lYWVmMmVkYjEwMWQg
UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAOcSsyiZ
IXqDukS5HolOkLOZh59L0AXUR5nHHEl2PYW7xMaTFdWrkA68y2l7KiXmEzwrAJ1K
fPpxTbGBmCOehwpKMMKEEHIEynsdlriSj/M6M0PXdwPqkuyRv9Jq0983qg1Ofyih
3maJZ4ym1p+oOi395umOYYzFgeU3q6tbnodlj9/wU/0d/Nkl1S0lHtkeU0v7MGtw
ucuzm+w0IyTaXe1t6wcF8n6CDhmUJaPBH1jUA9LMQuxL3nTGJpoHG/FgmSyPtukP
/3SJ4TpoLyC5GXx4tCPnhYgI2DGQTEvU4lCLbVfxdzDaJzzc3CHRvJPDJIe92Mub
cFowKuwWXmwcEf6rUiO3dwJPYpca32WIT4y5PoQ3QvEO9M1VU35Y+E+h9qfNESZ6
aEcarm1nfl+Q9NdGEZTY1tnqNJx3g/I7P/KEGYjvORoNk0ep2NtfZUvK9zHvg9j0
G8fHcE6CjlBPP5ORMCGiEa+Dw5uDa3NBl7SVt2n9le327LmQ4sOktoL4awIDAQAB
oz8wPTAdBgNVHQ4EFgQU0hMw7i9ulwAr+QwSkUpzxjwQwzkwDwYDVR0TBAgwBgEB
/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAHWLyV3w1m7RJk1d
zXzLAxHKm+4/162EasOM8zvTfU7uVPnyX1N/SnxVpTf00tUFeU74J4Qns1jvtCul
Hx2USyQXzhr9l7BtLeQmDrMsQy+MUSnZBoOAyIMLDg4C83TFAZsrjbt4c5vfI7O4
La17gWKlQnv4VcXvS6IxLXevSUHLmaG77OSlUSyk9YoA8AZ3Tx9TQzEfy1LaSzUE
kwZhg3KP2b0tpjanLm/CnQs5xIcFgsrUumxT7CFuxVH6pVeC9AO7qu5GYhylL7WC
ASvupuj25zZ6sAmHb/+sGNPEjBVh7nHPvGJE4g6UjRMwSHEnY7n/IQJFbm+n7/K/
vMz6A9aVzhsDcvg/NYiv2Ub2QtFLvqax2HKKOYJKMVpzJrhDNVPT2eRveLqHLVJ4
WismVh9lwXISI0QAGnNZgoQ298KAaCRJJ4DDgHTuV21miyp+UmDCnT/wHwoHDdZh
zUNNc2qfGuiCQe4NT8vgdlITVLqsKHIRZEtfTYEAejBVY3Qh1w==
-----END CERTIFICATE-----` || process.env.DB_CERTIFICATE.trim();
const DB_CON_URI = `mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST_URL}:${DB_PORT_NUM}/${DB_NAME}?ssl-mode=REQUIRED`;

//Netlify
const NETLIFY_END_POINT = "/.netlify/functions/api";

module.exports = {
  PORT_NUM,
  SHOPIFY_API_KEY,
  SHOPIFY_SECRET_KEY,
  SHOPIFY_API_TOKEN,
  SHOPIFY_API_SCOPES,
  SHOPIFY_SHOP_NAME,
  DB_HOST_URL,
  DB_NAME,
  DB_USERNAME,
  DB_PORT_NUM,
  DB_PASSWORD,
  DB_CON_URI,
  DB_CERTIFICATE,
  NETLIFY_END_POINT,
};
